-- Add new players
INSERT INTO players (name, nickname, role_id) VALUES
  ('Sergio', 'Sergio', 1),
  ('Sebastian', 'Sebastian', 1),
  ('Juan', 'Juan', 1),
  ('Jossua', 'Jossua', 1),
  ('Steven', 'Steven', 1),
  ('Azamat', 'Azamat', 1),
  ('Matt G', 'Matt G', 1),
  ('Adrian', 'Adrian', 1),
  ('Doctor', 'Doctor', 1),
  ('Luis', 'Luis', 1),
  ('Paarth', 'Paarth', 1),
  ('Mohammad', 'Mohammad', 1),
  ('Hessam', 'Hessam', 1),
  ('Larry', 'Larry', 1),
  ('Zabit', 'Zabit', 1),
  ('Bahador', 'Bahador', 1),
  ('M. Mansouri', 'M. Mansouri', 1),
  ('Tall Ali', 'Tall Ali', 1),
  ('Ali', 'Ali', 1),
  ('Alan', 'Alan', 1),
  ('Terry', 'Terry', 1),
  ('Luciano', 'Luciano', 1),
  ('Vini', 'Vini', 1),
  ('Sardar', 'Sardar', 1),
  ('John', 'John', 1),
  ('Kevin', 'Kevin', 1);
